# Generated by Django 4.1.7 on 2023-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
