# Generated by Django 4.1.7 on 2023-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='meridian',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=50),
        ),
    ]
