# Generated by Django 4.1.7 on 2023-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_games_date_games_price_games_meridian'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
