# Generated by Django 4.1.7 on 2023-05-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_games_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='games',
        ),
    ]
