# Generated by Django 4.1.7 on 2023-05-14 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_remove_gameselect_games_remove_gameselect_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('meridian', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=50)),
                ('Time', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('Address', models.TextField()),
                ('Price', models.IntegerField()),
                ('players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='GameSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.pitch'),
        ),
        migrations.AddField(
            model_name='games',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.sport'),
        ),
    ]
