# Generated by Django 4.1.7 on 2023-05-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_agerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Agerange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.agerange'),
        ),
    ]
