# Generated by Django 4.1.7 on 2023-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_games_agerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameselect',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameselect',
            name='createdat',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
