# Generated by Django 4.1.7 on 2023-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_gameselect_amount_gameselect_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='spot',
            field=models.IntegerField(default=0),
        ),
    ]
