# Generated by Django 4.1.7 on 2023-06-25 17:29

from django.db import migrations
import league.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_games_spot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', league.models.CustomUserManager()),
            ],
        ),
    ]
