# Generated by Django 4.1.7 on 2023-08-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='pitchmap',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
